# Generated by Django 3.2 on 2021-05-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('info_hash', models.CharField(max_length=200, null=True)),
                ('user_key', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
