# Generated by Django 3.2 on 2021-05-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='did',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='did_time_hash',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='wallet_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
