# Generated by Django 3.2 on 2021-05-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210520_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='wallet_key',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
