# Generated by Django 3.2 on 2021-05-22 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entry_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
