# Generated by Django 3.2 on 2021-05-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_entry_entry_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='admin_did',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
