# Generated by Django 3.2 on 2021-05-26 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_entry_admin_did'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='admin_did',
        ),
    ]
