# Generated by Django 3.2 on 2021-05-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_remove_entry_admin_did'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_did', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('name', models.CharField(max_length=30, null=True)),
                ('building_num', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
