# Generated by Django 3.2 on 2021-05-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
