# Generated by Django 3.2 on 2021-05-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='position',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
