# Generated by Django 3.2 on 2021-05-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_member_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kguinfo',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('info_hash', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
