# Generated by Django 3.2 on 2021-05-26 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_kguinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='container_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
