# Generated by Django 3.2 on 2021-05-27 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0012_member_container_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kguinfo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='info_hash',
        ),
    ]
